/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YoutubeLinkGeneratorRouteImport } from './routes/youtube-link-generator'
import { Route as WhatsappLinkGeneratorRouteImport } from './routes/whatsapp-link-generator'
import { Route as UtmLinkGeneratorRouteImport } from './routes/utm-link-generator'
import { Route as SlugGeneratorRouteImport } from './routes/slug-generator'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShortLinkGeneratorRouteImport } from './routes/short-link-generator'
import { Route as RickrollLinkGeneratorRouteImport } from './routes/rickroll-link-generator'
import { Route as ReferralLinkGeneratorRouteImport } from './routes/referral-link-generator'
import { Route as QrCodeLinkGeneratorRouteImport } from './routes/qr-code-link-generator'
import { Route as PremiumLinkGeneratorRouteImport } from './routes/premium-link-generator'
import { Route as MailtoLinkGeneratorRouteImport } from './routes/mailto-link-generator'
import { Route as GoogleReviewLinkGeneratorRouteImport } from './routes/google-review-link-generator'
import { Route as GoogleMapsLinkGeneratorRouteImport } from './routes/google-maps-link-generator'
import { Route as AffiliateLinkGeneratorRouteImport } from './routes/affiliate-link-generator'
import { Route as AddToCalendarLinkGeneratorRouteImport } from './routes/add-to-calendar-link-generator'
import { Route as IndexRouteImport } from './routes/index'

const YoutubeLinkGeneratorRoute = YoutubeLinkGeneratorRouteImport.update({
  id: '/youtube-link-generator',
  path: '/youtube-link-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatsappLinkGeneratorRoute = WhatsappLinkGeneratorRouteImport.update({
  id: '/whatsapp-link-generator',
  path: '/whatsapp-link-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const UtmLinkGeneratorRoute = UtmLinkGeneratorRouteImport.update({
  id: '/utm-link-generator',
  path: '/utm-link-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugGeneratorRoute = SlugGeneratorRouteImport.update({
  id: '/slug-generator',
  path: '/slug-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShortLinkGeneratorRoute = ShortLinkGeneratorRouteImport.update({
  id: '/short-link-generator',
  path: '/short-link-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const RickrollLinkGeneratorRoute = RickrollLinkGeneratorRouteImport.update({
  id: '/rickroll-link-generator',
  path: '/rickroll-link-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralLinkGeneratorRoute = ReferralLinkGeneratorRouteImport.update({
  id: '/referral-link-generator',
  path: '/referral-link-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const QrCodeLinkGeneratorRoute = QrCodeLinkGeneratorRouteImport.update({
  id: '/qr-code-link-generator',
  path: '/qr-code-link-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumLinkGeneratorRoute = PremiumLinkGeneratorRouteImport.update({
  id: '/premium-link-generator',
  path: '/premium-link-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const MailtoLinkGeneratorRoute = MailtoLinkGeneratorRouteImport.update({
  id: '/mailto-link-generator',
  path: '/mailto-link-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const GoogleReviewLinkGeneratorRoute =
  GoogleReviewLinkGeneratorRouteImport.update({
    id: '/google-review-link-generator',
    path: '/google-review-link-generator',
    getParentRoute: () => rootRouteImport,
  } as any)
const GoogleMapsLinkGeneratorRoute = GoogleMapsLinkGeneratorRouteImport.update({
  id: '/google-maps-link-generator',
  path: '/google-maps-link-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliateLinkGeneratorRoute = AffiliateLinkGeneratorRouteImport.update({
  id: '/affiliate-link-generator',
  path: '/affiliate-link-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const AddToCalendarLinkGeneratorRoute =
  AddToCalendarLinkGeneratorRouteImport.update({
    id: '/add-to-calendar-link-generator',
    path: '/add-to-calendar-link-generator',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-to-calendar-link-generator': typeof AddToCalendarLinkGeneratorRoute
  '/affiliate-link-generator': typeof AffiliateLinkGeneratorRoute
  '/google-maps-link-generator': typeof GoogleMapsLinkGeneratorRoute
  '/google-review-link-generator': typeof GoogleReviewLinkGeneratorRoute
  '/mailto-link-generator': typeof MailtoLinkGeneratorRoute
  '/premium-link-generator': typeof PremiumLinkGeneratorRoute
  '/qr-code-link-generator': typeof QrCodeLinkGeneratorRoute
  '/referral-link-generator': typeof ReferralLinkGeneratorRoute
  '/rickroll-link-generator': typeof RickrollLinkGeneratorRoute
  '/short-link-generator': typeof ShortLinkGeneratorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/slug-generator': typeof SlugGeneratorRoute
  '/utm-link-generator': typeof UtmLinkGeneratorRoute
  '/whatsapp-link-generator': typeof WhatsappLinkGeneratorRoute
  '/youtube-link-generator': typeof YoutubeLinkGeneratorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-to-calendar-link-generator': typeof AddToCalendarLinkGeneratorRoute
  '/affiliate-link-generator': typeof AffiliateLinkGeneratorRoute
  '/google-maps-link-generator': typeof GoogleMapsLinkGeneratorRoute
  '/google-review-link-generator': typeof GoogleReviewLinkGeneratorRoute
  '/mailto-link-generator': typeof MailtoLinkGeneratorRoute
  '/premium-link-generator': typeof PremiumLinkGeneratorRoute
  '/qr-code-link-generator': typeof QrCodeLinkGeneratorRoute
  '/referral-link-generator': typeof ReferralLinkGeneratorRoute
  '/rickroll-link-generator': typeof RickrollLinkGeneratorRoute
  '/short-link-generator': typeof ShortLinkGeneratorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/slug-generator': typeof SlugGeneratorRoute
  '/utm-link-generator': typeof UtmLinkGeneratorRoute
  '/whatsapp-link-generator': typeof WhatsappLinkGeneratorRoute
  '/youtube-link-generator': typeof YoutubeLinkGeneratorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-to-calendar-link-generator': typeof AddToCalendarLinkGeneratorRoute
  '/affiliate-link-generator': typeof AffiliateLinkGeneratorRoute
  '/google-maps-link-generator': typeof GoogleMapsLinkGeneratorRoute
  '/google-review-link-generator': typeof GoogleReviewLinkGeneratorRoute
  '/mailto-link-generator': typeof MailtoLinkGeneratorRoute
  '/premium-link-generator': typeof PremiumLinkGeneratorRoute
  '/qr-code-link-generator': typeof QrCodeLinkGeneratorRoute
  '/referral-link-generator': typeof ReferralLinkGeneratorRoute
  '/rickroll-link-generator': typeof RickrollLinkGeneratorRoute
  '/short-link-generator': typeof ShortLinkGeneratorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/slug-generator': typeof SlugGeneratorRoute
  '/utm-link-generator': typeof UtmLinkGeneratorRoute
  '/whatsapp-link-generator': typeof WhatsappLinkGeneratorRoute
  '/youtube-link-generator': typeof YoutubeLinkGeneratorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-to-calendar-link-generator'
    | '/affiliate-link-generator'
    | '/google-maps-link-generator'
    | '/google-review-link-generator'
    | '/mailto-link-generator'
    | '/premium-link-generator'
    | '/qr-code-link-generator'
    | '/referral-link-generator'
    | '/rickroll-link-generator'
    | '/short-link-generator'
    | '/sitemap.xml'
    | '/slug-generator'
    | '/utm-link-generator'
    | '/whatsapp-link-generator'
    | '/youtube-link-generator'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add-to-calendar-link-generator'
    | '/affiliate-link-generator'
    | '/google-maps-link-generator'
    | '/google-review-link-generator'
    | '/mailto-link-generator'
    | '/premium-link-generator'
    | '/qr-code-link-generator'
    | '/referral-link-generator'
    | '/rickroll-link-generator'
    | '/short-link-generator'
    | '/sitemap.xml'
    | '/slug-generator'
    | '/utm-link-generator'
    | '/whatsapp-link-generator'
    | '/youtube-link-generator'
  id:
    | '__root__'
    | '/'
    | '/add-to-calendar-link-generator'
    | '/affiliate-link-generator'
    | '/google-maps-link-generator'
    | '/google-review-link-generator'
    | '/mailto-link-generator'
    | '/premium-link-generator'
    | '/qr-code-link-generator'
    | '/referral-link-generator'
    | '/rickroll-link-generator'
    | '/short-link-generator'
    | '/sitemap.xml'
    | '/slug-generator'
    | '/utm-link-generator'
    | '/whatsapp-link-generator'
    | '/youtube-link-generator'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddToCalendarLinkGeneratorRoute: typeof AddToCalendarLinkGeneratorRoute
  AffiliateLinkGeneratorRoute: typeof AffiliateLinkGeneratorRoute
  GoogleMapsLinkGeneratorRoute: typeof GoogleMapsLinkGeneratorRoute
  GoogleReviewLinkGeneratorRoute: typeof GoogleReviewLinkGeneratorRoute
  MailtoLinkGeneratorRoute: typeof MailtoLinkGeneratorRoute
  PremiumLinkGeneratorRoute: typeof PremiumLinkGeneratorRoute
  QrCodeLinkGeneratorRoute: typeof QrCodeLinkGeneratorRoute
  ReferralLinkGeneratorRoute: typeof ReferralLinkGeneratorRoute
  RickrollLinkGeneratorRoute: typeof RickrollLinkGeneratorRoute
  ShortLinkGeneratorRoute: typeof ShortLinkGeneratorRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SlugGeneratorRoute: typeof SlugGeneratorRoute
  UtmLinkGeneratorRoute: typeof UtmLinkGeneratorRoute
  WhatsappLinkGeneratorRoute: typeof WhatsappLinkGeneratorRoute
  YoutubeLinkGeneratorRoute: typeof YoutubeLinkGeneratorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/youtube-link-generator': {
      id: '/youtube-link-generator'
      path: '/youtube-link-generator'
      fullPath: '/youtube-link-generator'
      preLoaderRoute: typeof YoutubeLinkGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whatsapp-link-generator': {
      id: '/whatsapp-link-generator'
      path: '/whatsapp-link-generator'
      fullPath: '/whatsapp-link-generator'
      preLoaderRoute: typeof WhatsappLinkGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/utm-link-generator': {
      id: '/utm-link-generator'
      path: '/utm-link-generator'
      fullPath: '/utm-link-generator'
      preLoaderRoute: typeof UtmLinkGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slug-generator': {
      id: '/slug-generator'
      path: '/slug-generator'
      fullPath: '/slug-generator'
      preLoaderRoute: typeof SlugGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/short-link-generator': {
      id: '/short-link-generator'
      path: '/short-link-generator'
      fullPath: '/short-link-generator'
      preLoaderRoute: typeof ShortLinkGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rickroll-link-generator': {
      id: '/rickroll-link-generator'
      path: '/rickroll-link-generator'
      fullPath: '/rickroll-link-generator'
      preLoaderRoute: typeof RickrollLinkGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referral-link-generator': {
      id: '/referral-link-generator'
      path: '/referral-link-generator'
      fullPath: '/referral-link-generator'
      preLoaderRoute: typeof ReferralLinkGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr-code-link-generator': {
      id: '/qr-code-link-generator'
      path: '/qr-code-link-generator'
      fullPath: '/qr-code-link-generator'
      preLoaderRoute: typeof QrCodeLinkGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium-link-generator': {
      id: '/premium-link-generator'
      path: '/premium-link-generator'
      fullPath: '/premium-link-generator'
      preLoaderRoute: typeof PremiumLinkGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mailto-link-generator': {
      id: '/mailto-link-generator'
      path: '/mailto-link-generator'
      fullPath: '/mailto-link-generator'
      preLoaderRoute: typeof MailtoLinkGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/google-review-link-generator': {
      id: '/google-review-link-generator'
      path: '/google-review-link-generator'
      fullPath: '/google-review-link-generator'
      preLoaderRoute: typeof GoogleReviewLinkGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/google-maps-link-generator': {
      id: '/google-maps-link-generator'
      path: '/google-maps-link-generator'
      fullPath: '/google-maps-link-generator'
      preLoaderRoute: typeof GoogleMapsLinkGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliate-link-generator': {
      id: '/affiliate-link-generator'
      path: '/affiliate-link-generator'
      fullPath: '/affiliate-link-generator'
      preLoaderRoute: typeof AffiliateLinkGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-to-calendar-link-generator': {
      id: '/add-to-calendar-link-generator'
      path: '/add-to-calendar-link-generator'
      fullPath: '/add-to-calendar-link-generator'
      preLoaderRoute: typeof AddToCalendarLinkGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddToCalendarLinkGeneratorRoute: AddToCalendarLinkGeneratorRoute,
  AffiliateLinkGeneratorRoute: AffiliateLinkGeneratorRoute,
  GoogleMapsLinkGeneratorRoute: GoogleMapsLinkGeneratorRoute,
  GoogleReviewLinkGeneratorRoute: GoogleReviewLinkGeneratorRoute,
  MailtoLinkGeneratorRoute: MailtoLinkGeneratorRoute,
  PremiumLinkGeneratorRoute: PremiumLinkGeneratorRoute,
  QrCodeLinkGeneratorRoute: QrCodeLinkGeneratorRoute,
  ReferralLinkGeneratorRoute: ReferralLinkGeneratorRoute,
  RickrollLinkGeneratorRoute: RickrollLinkGeneratorRoute,
  ShortLinkGeneratorRoute: ShortLinkGeneratorRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SlugGeneratorRoute: SlugGeneratorRoute,
  UtmLinkGeneratorRoute: UtmLinkGeneratorRoute,
  WhatsappLinkGeneratorRoute: WhatsappLinkGeneratorRoute,
  YoutubeLinkGeneratorRoute: YoutubeLinkGeneratorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
